name: Update GitHub Pages Content

on:
  
  schedule:
    # Runs at 5 minutes past every hour (adjust as needed)
    - cron: '40 * * * *'

jobs:
  fetch-and-update-content:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out your repo

    - name: Fetch HTML content from Cloud Function
      run: |
        curl -o index.html 'https://us-central1-cbbbot-413503.cloudfunctions.net/post_sports_odds_webpage'

    - name: Commit and push if changed
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update site content" -a || echo "No changes to commit"
        git push


